# Production override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d

version: '3.8'

services:
  app:
    # Override to use pre-built image instead of building locally
    image: ghcr.io/ellisbrookes/skedulaa:alpha-latest
    # Remove volumes for production (code is in the image)
    volumes: []
    # Override container name for production
    container_name: skedulaa-app-production
