version: '3'
services:
  db:
    image: mysql:8.0
    container_name: appointment-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - appointment-network
    ports:
      - "3306:3306"
    mem_limit: 2g
    mem_reservation: 1g
    cpus: 1

  app:
    build:
      context: .
    container_name: appointment-app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_KEY: ${APP_KEY}
    depends_on:
      - db
    networks:
      - appointment-network
    ports:
      - "8000:8000"

networks:
  appointment-network:
    driver: bridge

volumes:
  db-data:
    driver: local
