name: Run Laravel Tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, sqlite3
          coverage: xdebug

      - name: Create .env from .env.testing.example
        run: cp .env.testing.example .env

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Generate app key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
          STRIPE_SECRET: "sk_test_dummy_key_for_testing"

      - name: Run tests with coverage
        run: php artisan test --coverage --min=50
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
          STRIPE_SECRET: "sk_test_dummy_key_for_testing"
